image: docker:stable

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build . --tag etru/turn
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    - docker tag etru/turn etru/turn:$CI_COMMIT_SHORT_SHA
    - docker push etru/turn
